### PR TITLE
Initial gem

### PR DESCRIPTION
**Pull request by timonv**
A simple ruby gem that wraps our API.

The code mostly adheres to rubocop. Got to love minitest.

### CODE REVIEW

**Comment by timonv** [comment]
Note that YARD documentation is automatically created on rubydocs after a gem gets published to to rubygems.

**Comment by timonv** [comment]
As a side note outside of this PR discussion, I would like to use the gem in practice (ie the auto pr thing) before announcing it. Publishing is fine.

**Comment by timonv** [comment]
Quite likely there are still some gaps in the documentation and/or tests, if there's anything I missed, appreciated if it's pointed out :)

**Comment by mdemare** [comment]
Cool! +1

**Pull request merged**
